### Login as ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "fotismenos007@mail.ru",
	"password": "root123"
}

##################################################################################################################################################################

### delete an attachment -> ADMIN
DELETE http://localhost:8080/api/v1/attach/bed53248-0138-49aa-97d0-c49d4a566af1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ2NjI2ODI1LCJleHAiOjE3NDY2MzA0MjV9.Y8Xc-TICatLgBojYovwwOqzb2CWqzlCqNH17chlt4qgA7w5LsKGvTY7R-GHdqQQjELx50JAV4tUaLNGhcCY8WQ

### open an attachment -> ADMIN
GET http://localhost:8080/api/v1/attach/open/505d667f-16ef-4df5-b481-eb58e9ff9a4c
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ2NjM3MDgxLCJleHAiOjE3NDY2NDA2ODF9.IgE4pGu1bH0GvRjvOW2G2ZUPnSTR2aXw678AUfTN04Va2vaCOAt7h1MxRMZHhyf2h7mSBeTAVYNxNcLDlJCBQQ

### download an attachment -> ADMIN
GET http://localhost:8080/api/v1/attach/download/505d667f-16ef-4df5-b481-eb58e9ff9a4c
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ2NjM3MjU0LCJleHAiOjE3NDY2NDA4NTR9.zV9b6cYho9lIP_1pqRmf0L5B3lctaWFdPHqiYkxoUG9iKjeNA6y6q7V3iz2-zGlp8Le0yHPDgX8rBFItMtIL-A
