### Registration
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
	"firstName": "Akbar",
	"lastName": "Ahmad",
	"email": "akbarjondev007@gmail.com",
	"phoneNumber": "998945060749",
	"password": "root123"
}

### Verification
POST http://localhost:8080/api/v1/auth/verify-otp
Content-Type: application/json

{
	"userId": "6ac94650-6d8d-4269-aa19-88d04e030532",
	"otp": "035927"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}
