### Login as ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "fotismenos007@mail.ru",
	"password": "root123"
}

### Login as MANAGER & CUSTOMER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}

##################################################################################################################################################################

### create dish
POST http://localhost:8080/api/v1/dish
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3NDc4NjU3LCJleHAiOjE3NDc0ODIyNTd9.iFrulLGhqoGZj1ROJ2a7FF1bm78eopaB7JtDd-qu2DCttKxgBRNDN9CDxuqsdm-c42PYib8yFe6hSWTvJFFPeg
Content-Type: application/json

{
	"name": "Spicy seasoned seafood noodles",
	"price": 2.29,
	"quantityAvailable": 20,
	"dishCategory": "HOT",
	"photoId": "a75c90e2-e763-4625-92d4-b913016938d7"
}

### get all dishes sort, filter & pagination
GET http://localhost:8080/api/v1/dish/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3MzkzNDgwLCJleHAiOjE3NDczOTcwODB9.uFVk7h91KMCxVtss5I2qxAQoMc6RRNFqhhCwmYc22igcxAt9lNnKmJLIDd-yqq_PONapmAUkT7Tcbk4nXeEerA

### get dish by id
GET http://localhost:8080/api/v1/dish/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3Mzk3NDc1LCJleHAiOjE3NDc0MDEwNzV9.WwgAkgCrhcM6gEw9ts6qV3QqRDwcD1326K8rcnaiqmQm_w1bpuAkhHjVZyVXjPJl-QOeX6c-XNx2MQBOQmfO6A

### update dish
PUT http://localhost:8080/api/v1/dish/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3NDc4NjU3LCJleHAiOjE3NDc0ODIyNTd9.iFrulLGhqoGZj1ROJ2a7FF1bm78eopaB7JtDd-qu2DCttKxgBRNDN9CDxuqsdm-c42PYib8yFe6hSWTvJFFPeg
Content-Type: application/json

{
	"name": "seasoned seafood noodles",
	"price": 4.29,
	"quantityAvailable": 40,
	"dishCategory": null,
	"photoId": "6f9c4229-22ad-4866-9fbc-c9a2bfafcc81"
}

### delete dish (HARD & SOFT)
DELETE http://localhost:8080/api/v1/dish/1?deleteType=HARD
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3NDc4NjU3LCJleHAiOjE3NDc0ODIyNTd9.iFrulLGhqoGZj1ROJ2a7FF1bm78eopaB7JtDd-qu2DCttKxgBRNDN9CDxuqsdm-c42PYib8yFe6hSWTvJFFPeg
