### Login as ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "fotismenos007@mail.ru",
	"password": "root123"
}

### Login as MANAGER & CUSTOMER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}

##################################################################################################################################################################

### get all order items with filter, sort & pagination
GET http://localhost:8080/api/v1/order-items
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ4ODcxOTUwLCJleHAiOjE3NDg4NzU1NTB9.ygtks9u4OJmAcVdOvTDY6MRT1Bhv6KPKEB3Z7iARmPr3TvmdrgxYsS2uqUHGG1Qx-CVy37p2whb6uuHZoJKEQg

### get an order item by id
GET http://localhost:8080/api/v1/order-items/95e0c998-570a-48d8-bc35-befb97fdd39d
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ4OTY1MjA5LCJleHAiOjE3NDg5Njg4MDl9.SqbmYsQnHIwsq1MjGY_Pdn25SC7LAE0agI51xqT2BLVAgJkPEZv8swNgsfQMZ0usAL0ESR5p4TOOmm63aBTh4g
