### Login as ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "fotismenos007@mail.ru",
	"password": "root123"
}

### Login as MANAGER & CUSTOMER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}

##################################################################################################################################################################

### create order
POST http://localhost:8080/api/v1/order
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3ODMzODc0LCJleHAiOjE3NDc4Mzc0NzR9.kpWcPBhmtJovWeQse9khMnczgReot2tPibkm1mjUES61k5S9oHuyoJp354m0iCy5yRyAX8rjsgv9_jc0x2AyJw
Content-Type: application/json

{
	"discount": 1.0,
	"orderStatus": "PENDING",
	"customerId": "3e673bdd-a078-4bc7-a427-09963fed471c",
	"orderItemDtos": [
		{
			"quantity": 1,
			"price": 2.29,
			"note": "Prepare ASAP!!!",
			"orderType": "TO_GO",
			"dishId": 6
		},
		{
			"quantity": 2,
			"price": 3.67,
			"note": "Make it sweet :)",
			"orderType": "DINE_IN",
			"dishId": 7
		}
	]
}

### get all orders with filter, sort & pagination
GET http://localhost:8080/api/v1/order/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3NjU2NTg2LCJleHAiOjE3NDc2NjAxODZ9.ffnYIUq8wbwvajC_PdVpAA_c4gGDp46nTea50GXGSvNxoMB9QNRb6wenf8ITNTmpbF3GlsWWi9OU1c_-RfxXjw

### get order by id
GET http://localhost:8080/api/v1/order/5206e2a4-04b7-4e18-8364-8eff61fa671a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3NjU2NTg2LCJleHAiOjE3NDc2NjAxODZ9.ffnYIUq8wbwvajC_PdVpAA_c4gGDp46nTea50GXGSvNxoMB9QNRb6wenf8ITNTmpbF3GlsWWi9OU1c_-RfxXjw

### update orderStatus
PUT http://localhost:8080/api/v1/order/218ace10-8491-4247-8bf4-ea48c54535d4/status?orderStatus=CANCELED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIzZTY3M2JkZC1hMDc4LTRiYzctYTQyNy0wOTk2M2ZlZDQ3MWMiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9NQU5BR0VSIn1dLCJpYXQiOjE3NDc4MzQwNzgsImV4cCI6MTc0NzgzNzY3OH0.wzTf7HK1RDzNhLljGiubW884s3c9X9j_A2LcZhr1zDIbrvetRVohwFVzS4gB4BgRVSffXLwCmNWdMSWwtgHFiA

### delete order by id -> HARD || SOFT
DELETE http://localhost:8080/api/v1/order/5206e2a4-04b7-4e18-8364-8eff61fa671a?deleteType=HARD
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ3NzMwNjMyLCJleHAiOjE3NDc3MzQyMzJ9.yzIWCKqMRoKdlIXQ4ylrZB1mqreLgdX4bxHazeI_aAwZF82KgKSBUsiPRZZCTGOsmqo8mDAtsopea9VzllEehA
