### Login as ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "fotismenos007@mail.ru",
	"password": "root123"
}

### Login as CUSTOMER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}

##################################################################################################################################################################

### get any user's details -> ADMIN
GET http://localhost:8080/api/v1/user/f84fb107-6c79-4c24-abd1-42d01fd6733b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIzZTY3M2JkZC1hMDc4LTRiYzctYTQyNy0wOTk2M2ZlZDQ3MWMiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9XSwiaWF0IjoxNzQzNDA4NTgwLCJleHAiOjE3NDM0MTIxODB9.Fnuo-ch-Mbyhh5LOjX6M-bXCn-oat02GYrxJusCTUQsLRKchzeNSas12N1KI2UGtBYdLYSGs2su2vsgADld1rg

### get any user's details -> ADMIN
GET http://localhost:8080/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3QG1haWwucnUiLCJ1c2VySWQiOiJmODRmYjEwNy02Yzc5LTRjMjQtYWJkMS00MmQwMWZkNjczM2IiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9DVVNUT01FUiJ9LHsiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQzNDA4Njc3LCJleHAiOjE3NDM0MTIyNzd9.0GG782P1R9tI5BQyiu4v5cuFabl6Rcuhl1jbq8cjzhibbpFEjKmlsClNAUiqAEsShHRT8J9kxDJZLcD9Vw-TXA
